config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  get 'up' => 'rails/health#show', as: :rails_health_check
  root 'sms_alerts#index'
  post :send_sms, controller: :sms_alerts, action: :send_sms, as: 'send_sms'
  post '/message-status', to: 'twilio_webhooks#message_status'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  validates :body, presence: true
  validates :external_id, presence: true, uniqueness: true
  validates :status, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  validates :phone_number, format: { with: /\A\+\d{2}\d{9,15}\z/, message: 'invalid!' }
  validates :phone_number, uniqueness: { case_sensitive: false }
  after_commit :send_welcome_sms, on: %i[create update], if: -> { saved_change_to_phone_number? }
  has_many :messages, dependent: :destroy

  private

  def send_welcome_sms
    SendSmsJob.perform_async(id, phone_number, SIGN_UP_ALERT_TEXT, name)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[phone_number name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[phone_number name])
  end
end

app/controllers/sms_alerts_controller.rb
# frozen_string_literal: true

class SmsAlertsController < ApplicationController
  before_action :authenticate_user!

  def send_sms
    SendSmsJob.perform_in(SIDEKIQ_DELAY, current_user.id, current_user.phone_number, params[:msg], current_user.name)
    redirect_back fallback_location: root_path, notice: I18n.t('sms_alert_wait')
  end
end

app/controllers/twilio_webhooks_controller.rb
# frozen_string_literal: true

class TwilioWebhooksController < ApplicationController
  protect_from_forgery with: :null_session

  def message_status
    NotifySmsStatusJob.perform_in(SIDEKIQ_DELAY, params[:MessageSid], params[:MessageStatus])
    redirect_back fallback_location: root_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teletask</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.css" rel="stylesheet" />

  </head>
  <body>
    <%= render 'shared/navbar' if current_user %>
    <%= render partial: "shared/notifications" %>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <div id="messages"></div>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.js"></script>

  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="bg-blue-300 p-4 flex justify-between items-center">
  <div class="flex items-center">
    <span class="text-white font-bold text-xl">
      <%= image_tag("app-logo.png", alt: "Logo", class: "h-8 w-8 mr-2") %>
    </span>
  </div>
  <div class="flex items-center space-x-4">
    <%= button_to "Sign out", destroy_user_session_path, style: 'all: unset', class: 'nav-link', method: :delete %>
  </div>
</nav>

app/views/shared/_notifications.html.erb
<div
  id="toast-success"
  class="transition d-none transform duration-1000 absolute bottom-5 right-5 flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 text-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800" 
  role="alert"
  data-controller="notifications"
>
</div>

app/views/sms_alerts/index.html.erb
<div class="min-h-screen flex items-start justify-center mt-8">
  <div class="w-1/4 pr-4">
    <div class="bg-blue-100 p-4 mb-4 rounded-none shadow-md flex flex-col items-center text-center">
      <div class="mb-4">
        <%= image_tag "user-icon.png", alt: "User Image", class: "mb-2 rounded-full w-16 h-16 mx-auto" %>
        <p><strong>Name:</strong> <%= current_user.name %></p>
      </div>
      <div class="flex items-center justify-center space-x-4">
        <%= link_to "Edit", edit_user_registration_path, class: 'btn btn-warning' %>
        <%= button_to "Send Sms Alert", send_sms_path(msg: SUCCESS_MESSAGE), class: 'btn btn-primary', method: :post %>
      </div>
    </div>
  </div>
</div>